### ISSUE TITLE
compile protobuf files in conan

### ISSUE THREAD

**Issue by Phibedy** [Phibedy/LMS#130]
Atm it only works with gcc 4.8,
```
../liblmscore.so: undefined reference to `google::protobuf::MessageFactory::InternalRegisterGeneratedFile(char const*, void (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&))'
../liblmscore.so: undefined reference to `google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, google::protobuf::io::CodedOutputStream*)'
../liblmscore.so: undefined reference to `google::protobuf::DescriptorPool::FindFileByName(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
```

https://github.com/memsharded/conan-protobuf/issues/7
https://github.com/memsharded/conan-protobuf/issues/5

**Comment by fabolhak** [comment]
Building it on the Jetson with gcc 4.8 fails because of some weird segmentation fault in the compiler while building OpenCV. 

Building with gcc 5.4 (default compiler) : 

- OpenCV success :+1: 
- Protobuf  success :+1: 
- pugixml success :+1: 
- lms fails :-1: during linking:
```
[100%] Linking CXX executable bin/lms
liblmscore.so: undefined reference to `pugi::xml_node::path(char) const'
collect2: error: ld returned 1 exit status
CMakeFiles/lms.dir/build.make:95: recipe for target 'bin/lms' failed
make[2]: *** [bin/lms] Error 1
```
