### ISSUE TITLE
lms linker error with pugixml

### ISSUE THREAD

**Issue by fabolhak** [Phibedy/LMS#131]
Building the conan dependencies on the Jetson with gcc 4.8 fails because of some weird segmentation fault in the compiler while building OpenCV. 

Building with gcc 5.4 (default compiler) : 

- Eigen3 success :+1: 
- OpenCV success :+1:
- cereal success :+1: 
- gtest success :+1: 
- kalman success :+1: 
- tclap success :+1: 
- urg_network success :+1: 
- zlib success :+1:  
- Protobuf  success :+1: 
- pugixml success :+1: 
- lms fails during linking:
```
[100%] Linking CXX executable bin/lms
liblmscore.so: undefined reference to `pugi::xml_node::path(char) const'
collect2: error: ld returned 1 exit status
CMakeFiles/lms.dir/build.make:95: recipe for target 'bin/lms' failed
make[2]: *** [bin/lms] Error 1
```

sooo close :(

**Comment by Phibedy** [comment]
Maybe you still have pugixml compiled with gcc 4.8 and conan takes it because of any reason.
But don't worry, it won't work with gcc 5.4 anyway because of #130
